import { cropToCardBlob, svgToStorableBlob } from '../../image'
import type {
  CatalogRefineStep,
  CatalogResult,
  CatalogSearchOutcome,
  CatalogSource,
} from '../types'

/** One vendored sealed product. Generated by `scripts/build-booster-catalog.mjs`. */
interface BoosterRecord {
  id: string
  name: string
  setCode: string
  setName: string
  /** Scryfall set-symbol SVG (`icon_svg_uri`) — the fallback / identifying artwork. */
  iconUrl: string
}

// Lazy-loaded so the vendored catalogue (thousands of products) stays out of the
// initial bundle; it's fetched once, the first time the Boosters tab is opened.
let cache: Promise<BoosterRecord[]> | undefined
function catalogue(): Promise<BoosterRecord[]> {
  if (!cache) {
    cache = import('../../data/boosters.json').then((m) => m.default as BoosterRecord[])
  }
  return cache
}

/** Prefer name matches over set matches, and prefixes over mid-string hits. */
function rank(record: BoosterRecord, needle: string): number {
  const name = record.name.toLowerCase()
  const set = record.setName.toLowerCase()
  if (name.startsWith(needle)) return 0
  if (name.includes(needle)) return 1
  if (set.startsWith(needle)) return 2
  if (set.includes(needle)) return 3
  return 4
}

/**
 * Every product of a set repeats its set name (`"Bloomburrow Collector Booster"`),
 * and the set name is already shown on the subtitle line — so the product name
 * truncates to a useless `"Bloomburrow …"`. Drop the redundant prefix for display,
 * leaving the part that tells the products apart (`"Collector Booster"`). The full
 * `name` is kept for the committed collectible and the tooltip.
 */
function shortLabel(name: string, setName: string): string | undefined {
  const prefix = setName.toLowerCase()
  if (!name.toLowerCase().startsWith(prefix)) return undefined
  const rest = name.slice(setName.length).replace(/^[\s:–—-]+/, '')
  return rest || undefined
}

async function searchBoosters(query: string, signal: AbortSignal): Promise<CatalogSearchOutcome> {
  const all = await catalogue()
  // A newer keystroke may have superseded us while the catalogue loaded.
  if (signal.aborted) throw new DOMException('Aborted', 'AbortError')

  const needle = query.trim().toLowerCase()
  const results: CatalogResult[] = all
    .map((record) => ({ record, score: rank(record, needle) }))
    .filter(({ score }) => score < 4)
    .sort((a, b) => a.score - b.score || a.record.name.localeCompare(b.record.name))
    // Same generous cap as Scryfall: a popular set has many sealed products.
    .slice(0, 24)
    .map(({ record }) => ({
      id: record.id,
      name: record.name,
      label: shortLabel(record.name, record.setName),
      subtitle: record.setName,
      imageUrl: record.iconUrl,
    }))

  return results.length ? { status: 'results', results } : { status: 'empty' }
}

/** Only the Scryfall card fields the art picker reads. */
interface ScryfallCard {
  id: string
  name: string
  collector_number: string
  image_uris?: { art_crop?: string; normal?: string }
  card_faces?: { image_uris?: { art_crop?: string; normal?: string } }[]
}

/**
 * A booster's picture is just the illustration, so prefer Scryfall's `art_crop`
 * (art alone, no border or rules text) and fall back to the full `normal` scan.
 * Double-faced cards carry no top-level image_uris; the front face has them.
 */
function cardImage(card: ScryfallCard): string | undefined {
  const front = card.card_faces?.[0]?.image_uris
  return (
    card.image_uris?.art_crop ??
    front?.art_crop ??
    card.image_uris?.normal ??
    front?.normal
  )
}

// The set's card arts, fetched from Scryfall once and reused: the refine step is
// searchable, and re-hitting a rate-limited API on every keystroke would be both
// wasteful and prone to 429s. Keyed by set code.
const artCache = new Map<string, CatalogResult[]>()

/**
 * Fetch the set's distinct card arts (a booster's art is always a variant of one),
 * in collector order. Returns `null` when Scryfall is unreachable or the set has no
 * cards, so the caller can still offer the set symbol alone.
 */
async function loadSetArts(record: BoosterRecord, signal: AbortSignal): Promise<CatalogResult[] | null> {
  const cached = artCache.get(record.setCode)
  if (cached) return cached

  // order=set sorts by collector number; unique=art collapses reprints/finishes to
  // one entry per distinct illustration, which is what the user is choosing between.
  const url = `https://api.scryfall.com/cards/search?q=${encodeURIComponent(`set:${record.setCode}`)}&unique=art&order=set`

  let res: Response
  try {
    res = await fetch(url, { headers: { Accept: 'application/json' }, signal })
  } catch (err) {
    if ((err as Error).name === 'AbortError') throw err
    return null // Offline or blocked: fall back to the set symbol.
  }

  if (res.status === 404) return null // Scryfall's "no cards matched".
  if (res.status === 429) {
    throw new Error('Too many searches at once. Wait a moment and try again.')
  }
  if (!res.ok) throw new Error(`Scryfall returned an error (${res.status}). Try again shortly.`)

  const body = (await res.json()) as { data?: ScryfallCard[] }
  const arts = (body.data ?? []).flatMap<CatalogResult>((card) => {
    const imageUrl = cardImage(card)
    return imageUrl
      ? [{ id: card.id, name: card.name, subtitle: `#${card.collector_number}`, imageUrl, fit: 'cover' }]
      : []
  })

  artCache.set(record.setCode, arts)
  return arts
}

/**
 * The second step: given a picked booster, offer artworks to use as its picture —
 * the set's card arts (fetched once from Scryfall, then filtered by card name in
 * memory) with the set symbol prepended as an always-available fallback.
 */
const refineArtwork: CatalogRefineStep = {
  searchLabel: 'Pick the artwork',
  placeholder: 'Filter by card name',
  hint: 'Any card from this set, or its set symbol. No connection or no match? Use the symbol.',
  emptyLabel: 'No cards match that name.',
  // Local filter over an already-fetched list — no rate limit to dodge.
  debounceMs: 150,
  // Show the whole set immediately, then narrow as the user types.
  minQueryLength: 0,
  async run(picked, query, signal) {
    const all = await catalogue()
    if (signal.aborted) throw new DOMException('Aborted', 'AbortError')
    const record = all.find((r) => r.id === picked.id)
    if (!record) return { status: 'error', message: 'That product is no longer in the catalogue.' }

    // The set symbol is always offered first, so a clean, instant choice survives
    // even when Scryfall is unreachable or the set has no card arts.
    const symbol: CatalogResult = {
      id: `symbol:${record.setCode}`,
      name: 'Set symbol',
      subtitle: record.setName,
      imageUrl: record.iconUrl,
    }

    let arts: CatalogResult[] | null
    try {
      arts = await loadSetArts(record, signal)
    } catch (err) {
      if ((err as Error).name === 'AbortError') throw err
      return { status: 'error', message: (err as Error).message }
    }

    const needle = query.trim().toLowerCase()
    const results = [symbol, ...(arts ?? [])].filter(
      (r) => !needle || r.name.toLowerCase().includes(needle),
    )
    return results.length ? { status: 'results', results } : { status: 'empty' }
  },
}

/** Adds the same CORS cache-buster the card image path uses (see `mtg-cards`). */
function busted(url: string): string {
  return `${url}${url.includes('?') ? '&' : '?'}cors=${Date.now()}`
}

/**
 * Downloads a picked image and returns a storable WebP. The picture is either a
 * card art (Scryfall's `art_crop`, cropped to fill the portrait tile) or the set
 * symbol (an SVG rasterised onto a light coin, since it's drawn black and would
 * vanish on the dark tiles).
 */
async function fetchImage(result: CatalogResult, signal: AbortSignal): Promise<Blob> {
  const isSvg = /\.svg(\?|$)/i.test(result.imageUrl)
  const res = await fetch(busted(result.imageUrl), { signal, mode: 'cors' })
  if (!res.ok) throw new Error(`Could not download that picture (${res.status}).`)
  const blob = await res.blob()
  return isSvg ? svgToStorableBlob(blob) : cropToCardBlob(blob)
}

/**
 * The MTG booster catalogue source: an offline, in-memory search over MTGJSON
 * sealed products vendored at build time. There is no public API that serves
 * sealed-product artwork, so a pick opens `refine` — the set's card arts (a
 * booster's art is always a variant of one), filterable by card name, with the set
 * symbol as a fallback. See `docs/architecture.md`.
 */
export const mtgBoostersSource: CatalogSource = {
  key: 'boosters',
  label: 'Boosters',
  searchLabel: 'Search sealed products',
  placeholder: 'Foundations',
  hint: 'Booster boxes, bundles and packs. Matched offline; pick its artwork next.',
  emptyLabel: 'No sealed products match that name.',
  // Local search, so no rate limit to dodge — just enough to skip mid-word churn.
  debounceMs: 150,
  search: searchBoosters,
  refine: refineArtwork,
  fetchImage,
}
