import { svgToStorableBlob, toStorableBlob } from '../image'
import type { CatalogResult, CatalogSearchOutcome, CatalogSource } from './types'

/** One vendored sealed product. Generated by `scripts/build-booster-catalog.mjs`. */
interface BoosterRecord {
  id: string
  name: string
  setCode: string
  setName: string
  /** Scryfall set-symbol SVG (`icon_svg_uri`) — the fallback / identifying artwork. */
  iconUrl: string
}

// Lazy-loaded so the vendored catalogue (thousands of products) stays out of the
// initial bundle; it's fetched once, the first time the Boosters tab is opened.
let cache: Promise<BoosterRecord[]> | undefined
function catalogue(): Promise<BoosterRecord[]> {
  if (!cache) {
    cache = import('../data/boosters.json').then((m) => m.default as BoosterRecord[])
  }
  return cache
}

/** Prefer name matches over set matches, and prefixes over mid-string hits. */
function rank(record: BoosterRecord, needle: string): number {
  const name = record.name.toLowerCase()
  const set = record.setName.toLowerCase()
  if (name.startsWith(needle)) return 0
  if (name.includes(needle)) return 1
  if (set.startsWith(needle)) return 2
  if (set.includes(needle)) return 3
  return 4
}

async function searchBoosters(query: string, signal: AbortSignal): Promise<CatalogSearchOutcome> {
  const all = await catalogue()
  // A newer keystroke may have superseded us while the catalogue loaded.
  if (signal.aborted) throw new DOMException('Aborted', 'AbortError')

  const needle = query.trim().toLowerCase()
  const results: CatalogResult[] = all
    .map((record) => ({ record, score: rank(record, needle) }))
    .filter(({ score }) => score < 4)
    .sort((a, b) => a.score - b.score || a.record.name.localeCompare(b.record.name))
    // Same generous cap as Scryfall: a popular set has many sealed products.
    .slice(0, 24)
    .map(({ record }) => ({
      id: record.id,
      name: record.name,
      subtitle: record.setName,
      imageUrl: record.iconUrl,
    }))

  return results.length ? { status: 'results', results } : { status: 'empty' }
}

/** Only the Scryfall card fields the art picker reads. */
interface ScryfallCard {
  id: string
  name: string
  collector_number: string
  image_uris?: { normal?: string }
  card_faces?: { image_uris?: { normal?: string } }[]
}

/** Double-faced cards carry no top-level image_uris; the front face has it. */
function cardImage(card: ScryfallCard): string | undefined {
  return card.image_uris?.normal ?? card.card_faces?.[0]?.image_uris?.normal
}

/**
 * The second step: given a picked booster, offer artworks to use as its picture.
 * A booster's art is always a variant of a card from its set, so we surface that
 * set's distinct card arts from Scryfall, in collector-number order (`order=set`),
 * with the set symbol prepended as an always-available fallback. Scryfall's
 * per-set search is a live call, but it only fires once — on a pick, not per key.
 */
async function refineBooster(
  result: CatalogResult,
  signal: AbortSignal,
): Promise<CatalogSearchOutcome> {
  const all = await catalogue()
  if (signal.aborted) throw new DOMException('Aborted', 'AbortError')
  const record = all.find((r) => r.id === result.id)
  if (!record) return { status: 'error', message: 'That product is no longer in the catalogue.' }

  // The set symbol is always offered first, so a clean, instant choice survives
  // even when Scryfall is unreachable or the set has no card arts.
  const symbol: CatalogResult = {
    id: `symbol:${record.setCode}`,
    name: 'Set symbol',
    subtitle: record.setName,
    imageUrl: record.iconUrl,
  }

  // order=set sorts by collector number; unique=art collapses reprints/finishes to
  // one entry per distinct illustration, which is what the user is choosing between.
  const url = `https://api.scryfall.com/cards/search?q=${encodeURIComponent(`set:${record.setCode}`)}&unique=art&order=set`

  let res: Response
  try {
    res = await fetch(url, { headers: { Accept: 'application/json' }, signal })
  } catch (err) {
    if ((err as Error).name === 'AbortError') throw err
    // Offline or blocked: still let the user take the set symbol or upload instead.
    return { status: 'results', results: [symbol] }
  }

  // 404 is Scryfall's "no cards matched" — offer the symbol alone rather than erroring.
  if (res.status === 404) return { status: 'results', results: [symbol] }
  if (res.status === 429) {
    return { status: 'error', message: 'Too many searches at once. Wait a moment and try again.' }
  }
  if (!res.ok) {
    return { status: 'error', message: `Scryfall returned an error (${res.status}). Try again shortly.` }
  }

  const body = (await res.json()) as { data?: ScryfallCard[] }
  const arts = (body.data ?? []).flatMap<CatalogResult>((card) => {
    const imageUrl = cardImage(card)
    return imageUrl
      ? [{ id: card.id, name: card.name, subtitle: `#${card.collector_number}`, imageUrl }]
      : []
  })

  return { status: 'results', results: [symbol, ...arts] }
}

/** Adds the same CORS cache-buster the card image path uses (see `scryfall.ts`). */
function busted(url: string): string {
  return `${url}${url.includes('?') ? '&' : '?'}cors=${Date.now()}`
}

/**
 * Downloads a picked image and returns a storable WebP. The picture is either a
 * card art (a raster JPEG) or the set symbol (an SVG that must be rasterised onto
 * a light coin, since it's drawn black and would vanish on the dark tiles).
 */
async function fetchImage(result: CatalogResult, signal: AbortSignal): Promise<Blob> {
  const isSvg = /\.svg(\?|$)/i.test(result.imageUrl)
  const res = await fetch(busted(result.imageUrl), { signal, mode: 'cors' })
  if (!res.ok) throw new Error(`Could not download that picture (${res.status}).`)
  const blob = await res.blob()
  return isSvg ? svgToStorableBlob(blob) : toStorableBlob(blob)
}

/**
 * The booster catalogue source: an offline, in-memory search over MTGJSON sealed
 * products vendored at build time. There is no public API that serves sealed-product
 * artwork, so a pick opens `refine` — the set's card arts (a booster's art is always
 * a variant of one) in collector order, with the set symbol as a fallback. See
 * `docs/architecture.md`.
 */
export const boosterSource: CatalogSource = {
  key: 'boosters',
  label: 'Boosters',
  searchLabel: 'Search sealed products',
  placeholder: 'Foundations',
  hint: 'Booster boxes, bundles and packs. Matched offline; pick its artwork next.',
  fetchingLabel: 'Fetching the picture…',
  emptyLabel: 'No sealed products match that name.',
  // Local search, so no rate limit to dodge — just enough to skip mid-word churn.
  debounceMs: 150,
  search: searchBoosters,
  refine: refineBooster,
  fetchImage,
}
